#!/bin/bash

# This script can be safefuly run multiple times on the same machine.

# It installs, upgrades, or skips packages
# based on what is already installed on the machine.

# It then creates symlinks of the config files in this repo
# to the `~/` (`$HOME`) directory.

# Tested on:
#  - OSX El Capitan (10.11)
#  - macOS High Sierra (10.13)

# shellcheck disable=SC2154
trap 'ret=$?; test $ret -ne 0 && echo "failed" >&2; exit $ret' EXIT

set -e

HOMEBREW_PREFIX="/usr/local"

if [ -d "$HOMEBREW_PREFIX" ]; then
  if ! [ -r "$HOMEBREW_PREFIX" ]; then
    sudo chown -R "$LOGNAME:admin" /usr/local
  fi
else
  sudo mkdir "$HOMEBREW_PREFIX"
  sudo chflags norestricted "$HOMEBREW_PREFIX"
  sudo chown -R "$LOGNAME:admin" "$HOMEBREW_PREFIX"
fi

if ! command -v brew >/dev/null; then
  echo "Installing Homebrew..."
    curl -fsS \
      'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby

    export PATH="/usr/local/bin:$PATH"
fi

echo "Updating Homebrew formulae..."
brew update
brew bundle --file=- <<EOF
tap "homebrew/services"
tap "cloudfoundry/tap"
tap "caskroom/versions"

cask "cakebrew"
cask "java8"

brew "git"
brew "jq"
brew "openssl"
brew "the_silver_searcher"
brew "tmux"
brew "vim"
brew "watch"
cask "ngrok"
brew "bash-completion"
brew "cf-cli"
brew "jenv"
brew "python@2"
EOF

echo "Cleaning up old Homebrew formulae..."
brew cleanup
brew cask cleanup

declare -a bash_completion=("git-prompt.sh" "git-completion.bash")
for file in "${bash_completion[@]}"
do
  if [ -f "/usr/local/etc/bash_completion.d/$file" ]; then
      grep -q -F "source /usr/local/etc/bash_completion.d/$file" ~/.bash_profile || echo "source /usr/local/etc/bash_completion.d/$file" >> ~/.bash_profile
  fi
done

# export CLICOLOR=1
# export GIT_PS1_SHOWDIRTYSTATE=1
# PS1='[\u@\h \W$(__git_ps1 " (%s)")]\$ '

# Enable CLI colors if not present

# shellcheck disable=SC2016
grep -q -F "CLICOLOR=1" ~/.bash_profile             || echo "CLICOLOR=1" >> ~/.bash_profile

# shellcheck disable=SC2016
grep -q -F '$HOME/.jenv/bin' ~/.bash_profile        || echo 'export PATH=""$HOME/.jenv/bin:$PATH"' >> ~/.bash_profile

# shellcheck disable=SC2016
grep -q -F 'eval "$(jenv init -)"' ~/.bash_profile  || echo 'eval "$(jenv init -)"' >> ~/.bash_profile

# shellcheck disable=SC2016
grep -q -F 'export PATH="/usr/local/opt/sqlite/bin:$PATH"' ~/.bash_profile || echo 'export PATH="/usr/local/opt/sqlite/bin:$PATH"' >> ~/.bash_profile

# shellcheck $HOME=/home/user
source "$HOME/.bash_profile"

if [ -f "$HOME/.macbook.local" ]; then
  bash "$HOME/.macbook.local"
fi
