#!/bin/bash

# This script can be safefuly run multiple times on the same machine.

# It installs, upgrades, or skips packages
# based on what is already installed on the machine.

# It then creates symlinks of the config files in this repo
# to the `~/` (`$HOME`) directory.

# Tested on:
#  - OSX El Capitan (10.11)
#  - macOS High Sierra (10.13)

# shellcheck disable=SC2154
trap 'ret=$?; test $ret -ne 0 && echo "failed" >&2; exit $ret' EXIT

set -e

HOMEBREW_PREFIX="/usr/local"

if [ -d "$HOMEBREW_PREFIX" ]; then
  if ! [ -r "$HOMEBREW_PREFIX" ]; then
    sudo chown -R "$LOGNAME:admin" /usr/local
  fi
else
  sudo mkdir "$HOMEBREW_PREFIX"
  sudo chflags norestricted "$HOMEBREW_PREFIX"
  sudo chown -R "$LOGNAME:admin" "$HOMEBREW_PREFIX"
fi

if ! command -v brew >/dev/null; then
  echo "Installing Homebrew..."
    curl -fsS \
      'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby

    export PATH="/usr/local/bin:$PATH"
fi

echo "Updating Homebrew formulae..."
brew update
brew bundle --file=- <<EOF
tap "homebrew/services"
cask "cakebrew"

# Unix
brew "git"
brew "jq"
brew "openssl"
brew "the_silver_searcher"
brew "tmux"
brew "vim", args: ["without-ruby"]
brew "watch"
cask "ngrok"
EOF

echo "Cleaning up old Homebrew formulae..."
brew cleanup
brew cask cleanup

echo "Symlinking dotfiles..."
echosymlink() {
  echo "$2 -> $1"
  ln -sf "$1" "$2"
}

if [ -d "$HOME/.asdf" ]; then
  echo "Upgrading ASDF version manager..."
  (
    cd "$HOME/.asdf"
    git pull origin master
  )
else
  echo "Installing ASDF version manager..."
  git clone https://github.com/asdf-vm/asdf.git "$HOME/.asdf"

  echo -e '\n. $HOME/.asdf/asdf.sh' >> ~/.bash_profile
  echo -e '\n. $HOME/.asdf/completions/asdf.bash' >> ~/.bash_profile
fi

# shellcheck source=/dev/null
. "$HOME/.asdf/asdf.sh"

asdf_plugin_add() {
  local name="$1"
  local source="$2"

  if ! asdf plugin-list | grep -Fq "$name"; then
    asdf plugin-add "$name" "$source"
  fi
}

asdf_install() {
  local language="$1"
  local version="$2"

  if ! asdf list "$language" | grep -Fq "$version"; then
    asdf install "$language" "$version"
    asdf global "$language" "$version"
  fi
}

echo "Installing Node..."
asdf_plugin_add "nodejs" "https://github.com/asdf-vm/asdf-nodejs"
export NODEJS_CHECK_SIGNATURES=no
asdf_install "nodejs" "8.9.0"

echo "Installing Java and Maven..."
asdf_plugin_add "java" "https://github.com/skotchpine/asdf-java"
asdf_install "java" "8.161"
asdf_plugin_add "maven" "https://github.com/skotchpine/asdf-maven"
asdf_install "maven" "3.3.9"


if [ -f "$HOME/.macbook.local" ]; then
  bash "$HOME/.macbook.local"
fi
